[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_workspace = "7eKDiZL6sPH4tKUkNjyjQeL7crKPoTXxVG3w5VGC1CJB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'solana_id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
