[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pacanele = "A3NxPbGv9f9y6j7mEmMeptZp7n8CYYyJxZeuMde68Gi6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
